[project]
name = "pacemaker"
version = "0.1.0"
repository = "https://github.com/mhatzl/pacemaker"

[[requirements]]
root = "doc/requirements.md"
origin = "https://github.com/mhatzl/pacemaker/blob/main/doc/requirements.md"

[[traces]]
root = ""
lsif_data = ["lsif.json"]

[coverage]
files = ["coverage.json"]

[review]
files = ["reviews/v0.1.0_review.toml"]
